### ISSUE TITLE
Swagger API path config doesnt work in boot.yaml

### ISSUE THREAD

**Issue by aaydinyan** [rookie-ninja/rk-boot#44]
I am trying to set a custom swagger api path, but it works only for default "sw" path.

**To Reproduce**
Set config in boot.yaml file:
`sw:
      enabled: true 
      path: "api-docs"
     jsonPath: "docs"
`

**Comment by dongxuny** [comment]
@aaydinyan It is a bug SwEntry in rk-xxx series. It is not a big changes.

I will fix the bug and bump up version of rk-xxx series by the end of today. I guess it may take me couple of hours to fix the bug, test and bump up version.

I will leave detailed message here as soon as I bump up the version.

**Comment by dongxuny** [comment]
# Problem description
sw.path is not working properly.

# Root cause
Swagger path variable in swagger file handler in SwEntry was hard coded as "/sw". It needs to be replaced by SwEntry.Path.

# Commits of bug fix
| pkg | commits |
| --- | --- |
| rk-boot | #45 |
| rk-echo | [be22d93ff2505b915ecf53f156e9a0da2cd42ecc](https://github.com/rookie-ninja/rk-echo/commit/be22d93ff2505b915ecf53f156e9a0da2cd42ecc) |
| rk-fiber | [c2ca03c729939784428c7a01f662c80aaac1554c](https://github.com/rookie-ninja/rk-fiber/commit/c2ca03c729939784428c7a01f662c80aaac1554c) |
|  rk-gf | [42c095eeb1858229c34bb753b7816f501c266d6a](https://github.com/rookie-ninja/rk-gf/commit/42c095eeb1858229c34bb753b7816f501c266d6a) |
| rk-gin | [bf7c44abcbf5d806bbf794505224849b1675a471](https://github.com/rookie-ninja/rk-gin/commit/bf7c44abcbf5d806bbf794505224849b1675a471) |
| rk-grpc | [1aa48642c33bb10b6aa4c3fdcb2d2c1c9d938112](https://github.com/rookie-ninja/rk-grpc/commit/1aa48642c33bb10b6aa4c3fdcb2d2c1c9d938112) |
| rk-mux | [e982ac2817cdc5fea2253f1a645141eea0755a12](https://github.com/rookie-ninja/rk-mux/commit/e982ac2817cdc5fea2253f1a645141eea0755a12) |
| rk-zero | [251b11b8f464ca41b6469b6fc6f46a2d1b20485e](https://github.com/rookie-ninja/rk-zero/commit/251b11b8f464ca41b6469b6fc6f46a2d1b20485e) |

Otherwise, fixed grpc-gateway option issues caused by new grpc-gateway version. [commit](https://github.com/rookie-ninja/rk-grpc/commit/80fb16b73795121c05ae75346c4c0f1043dfc14a)

# Please bump up to newest version as bellow
Please choose web framework to import. From v1.4.x, no need to import all web frameworks at once.

| Frameworks | Stage | Tag | Installation | Dependency |
| --- | --- | --- | --- | --- |
| [Gin](https://github.com/gin-gonic/gin) | Stable | v1.2.14 | go get github.com/rookie-ninja/rk-boot/gin | [rk-gin](https://github.com/rookie-ninja/rk-gin) |
| [gRPC](https://grpc.io/)  | Stable | v1.2.18 | go get github.com/rookie-ninja/rk-boot/grpc | [rk-grpc](https://github.com/rookie-ninja/rk-grpc) |
| [Echo](https://github.com/labstack/echo)  | Stable | v0.0.8 | go get github.com/rookie-ninja/rk-boot/echo | [rk-echo](https://github.com/rookie-ninja/rk-echo) |
| [GoFrame](https://github.com/gogf/gf)  | Stable | v0.0.5 | go get github.com/rookie-ninja/rk-boot/gf | [rk-gf](https://github.com/rookie-ninja/rk-gf) |
| [Fiber](https://github.com/gofiber/fiber) | Testing | v0.0.3 | go get github.com/rookie-ninja/rk-boot/fiber | [rk-fiber](https://github.com/rookie-ninja/rk-fiber) |
| [go-zero](https://github.com/zeromicro/go-zero) | Testing | v0.0.2 | go get github.com/rookie-ninja/rk-boot/zero | [rk-zero](https://github.com/rookie-ninja/rk-zero) |
| [GorillaMux](https://github.com/gorilla/mux) | Testing | v0.0.2 | go get github.com/rookie-ninja/rk-boot/mux | [rk-mux](https://github.com/rookie-ninja/rk-mux) |

**_Please reopen this issue if any problems related to this_**

**Comment by dongxuny** [comment]
@aaydinyan Please import new version rk-boot as needed. Reopen this issue if problems exists related to this problem. 

Thanks
